### PR TITLE
Add consolidate migrations tool

### LINKED ISSUE #1: Create util to consolidate existing migrations
Could take a look at this : 
- https://github.com/BigRoomStudios/schwifty-migrate-diff
- https://github.com/mattjcowan/knex-schema-reader

### PR DESCRIPTION
**Pull request by rohit-gohri**
Closes #1

### CODE REVIEW

**Comment by rohit-gohri** [comment]
## TODO:
- Add option to cli
- Add tests using something like https://migra.djrobstep.com/quickstart/

**Comment by rohit-gohri** [comment]
@hit12369 Reminder

**Comment by rohit-gohri** [comment]
TODO:
- Parse enum too

**Comment by rohit-gohri** [comment]
@hit12369 enum is done, also added support for gin type index.
Partitions can be done later.

**Comment by hit12369** [comment]
Conflicts need to be resolved, then it can be merged.

**Comment by rohit-gohri** [comment]
> Conflicts need to be resolved, then it can be merged.

Resolved

**Pull request merged**
